### ISSUE TITLE
RFE: expext to get the skupper version and username

### ISSUE THREAD

**Issue by rbaumgar** [skupperproject/skupper-console#209]
**Describe the bug**
I would expect to get the skupper version for each site on the console.
If I confige "--console-auth openshift" I would expect to get the username.

**To Reproduce**

1. Go to 'skupper console'
2. Click on every menu item without any version and user information

**Expected behavior**
Get the skupper version displayed on every site.
Get the username on the top.

**Screenshots**
na

**Comment by bartoval** [comment]
Thanks @rbaumgar ,
The version of the site was already planned. It should be released soon
I was wondering if you have a particular use case where you need to display the username

**Comment by rbaumgar** [comment]
@bartoval currently I have no use case for the username. But When I should login into a system, I expect to show the username on the UI.
