### ISSUE TITLE
Hide protocol column on Addresses tab

### ISSUE THREAD

**Issue by pwright** [skupperproject/skupper-console#87]
given the separation of protocol adaptors, maybe remove 'Protocol' column?

![image](https://user-images.githubusercontent.com/5154224/223752814-9c82bc7b-6c73-4baa-a119-2fabaadfe3b9.png)

**Comment by bartoval** [comment]
Protocol can be http or http2, we need this column to see this difference. 
Because they are part of the same family I think it will be better keep them in the same table.
